# Mago configuration file
# For more information, see https://mago.carthage.software/#/getting-started/configuration
php_version = "8.1.0"

[source]
paths = ["src/", "tests/"]
includes = ["vendor"]
excludes = ["src/Glob.php"]

[format]
print_width = 120
tab_width = 4
use_tabs = false

[linter]
default_plugins = true
plugins = ["symfony", "php-unit"]
