<?php

declare(strict_types=1);

namespace Stolt\LeanPackage\Gitattributes;

use Stolt\LeanPackage\Exceptions\GitattributesCreationFailed;

final class FileRepository
{
    public const HEADER_OVERWRITE_MODE_GENERATED = 'generated';
    public const HEADER_OVERWRITE_MODE_MODIFIED = 'modified';
    public const HEADER_OVERWRITE_MODE_REFORMATTED = 'reformatted';

    public const GENERATED_HEADER = '# This file was generated by the lean package validator (http://git.io/lean-package-validator).';
    public const MODIFIED_HEADER  = '# This file was partly modified by the lean package validator (http://git.io/lean-package-validator).';
    public const REFORMATTED_HEADER  = '# This file was reformatted by the lean package validator (http://git.io/lean-package-validator).';

    private string $workingDirectory;

    public function __construct(string $workingDirectory = '')
    {
        if ($workingDirectory === '' && \defined('WORKING_DIRECTORY')) {
            $workingDirectory = WORKING_DIRECTORY;
        }

        if ($workingDirectory === '' && !\defined('WORKING_DIRECTORY')) {
            $workingDirectory = \getcwd();
        }

        $this->workingDirectory = $workingDirectory;
    }

    public function setWorkingDirectory(string $workingDirectory): self
    {
        $this->workingDirectory = $workingDirectory;
        return $this;
    }

    public function getWorkingDirectory(): string
    {
        return $this->workingDirectory;
    }

    private function getFilePath(): string
    {
        return $this->workingDirectory . DIRECTORY_SEPARATOR . '.gitattributes';
    }

    public function getGitattributesContent(): string
    {
        return (string) \file_get_contents($this->getFilePath());
    }

    /**
     * Create the gitattributes file.
     *
     * @param  string  $content The content of the gitattributes file
     * @param  bool    $withHeader Whether to prepend the generated header
     * @throws GitattributesCreationFailed
     * @return string
     *
     */
    public function createGitattributesFile(string $content, bool $withHeader = true): string
    {
        // Ensure the generated or modified by header is present when requested
        if ($withHeader) {
            $content = $this->applyOverwriteHeaderPolicy($content);
        }

        $bytesWritten = file_put_contents($this->getFilePath(), $content);

        if ($bytesWritten) {
            $content = 'Created a .gitattributes file with the shown content:'
                . PHP_EOL . '<info>' . $content . '</info>';

            return PHP_EOL . PHP_EOL . $content;
        }

        $message = 'Creation of .gitattributes file failed.';
        throw new GitattributesCreationFailed($message);
    }

    /**
     * Overwrite an existing gitattributes file.
     *
     * @param  string  $content The content of the gitattributes file
     * @throws GitattributesCreationFailed
     * @return string
     *
     */
    public function overwriteGitattributesFile(string $content): string
    {
        // Apply header policy before writing (generated → partly modified).
        $content = $this->applyOverwriteHeaderPolicy($content);

        $bytesWritten = file_put_contents($this->getFilePath(), $content);

        if ($bytesWritten) {
            $content = 'Overwrote it with the shown content:'
                . PHP_EOL . '<info>' . $content . '</info>';

            return PHP_EOL . PHP_EOL . $content;
        }

        $message = 'Overwrite of .gitattributes file failed.';
        throw new GitattributesCreationFailed($message);
    }

    public function overwriteGitattributesFileFormatted(string $content): string
    {
        // Apply header policy before writing (generated → partly modified → reformatted).
        $content = $this->applyOverwriteHeaderPolicy($content, self::HEADER_OVERWRITE_MODE_REFORMATTED);

        $bytesWritten = file_put_contents($this->getFilePath(), $content);

        if ($bytesWritten !== false) {
            return '';
        }

        $message = 'Overwrite of .gitattributes file failed.';
        throw new GitattributesCreationFailed($message);
    }

    /**
     * Prepare .gitattributes content for overwriting by adjusting the header.
     * If the present file contains the "generated by" header, replace it with
     * the "partly modified by" header in the given content-to-write.
     */
    public function applyOverwriteHeaderPolicy(string $contentToWrite, string $overwriteHeaderMode = self::HEADER_OVERWRITE_MODE_GENERATED): string
    {
        $gitattributesPath = $this->getFilePath();

        if (!\is_file($gitattributesPath)) {
            return self::GENERATED_HEADER . PHP_EOL . PHP_EOL . $contentToWrite;
        }

        if ($overwriteHeaderMode === self::HEADER_OVERWRITE_MODE_REFORMATTED) {
            if (\str_contains($contentToWrite, self::MODIFIED_HEADER)) {
                return \str_replace(self::MODIFIED_HEADER, self::REFORMATTED_HEADER, $contentToWrite);
            }

            if (\str_contains($contentToWrite, self::GENERATED_HEADER)) {
                return \str_replace(self::GENERATED_HEADER, self::REFORMATTED_HEADER, $contentToWrite);
            }

            if (\str_contains($contentToWrite, self::REFORMATTED_HEADER)) {
                return $contentToWrite;
            }

            return self::REFORMATTED_HEADER . PHP_EOL . PHP_EOL . $contentToWrite;
        }

        if (\str_contains($contentToWrite, self::GENERATED_HEADER)) {
            return \str_replace(self::GENERATED_HEADER, self::MODIFIED_HEADER, $contentToWrite);
        }

        if ((\str_contains($contentToWrite, self::MODIFIED_HEADER) === false) && (\str_contains($contentToWrite, self::GENERATED_HEADER) === false)) {
            return self::MODIFIED_HEADER . PHP_EOL . PHP_EOL . $contentToWrite;
        }

        return $contentToWrite;
    }
}
