<?php

declare(strict_types=1);

namespace Stolt\LeanPackage\Tests\Commands;

use PHPUnit\Framework\Attributes\Test;
use Stolt\LeanPackage\Analyser;
use Stolt\LeanPackage\Commands\CreateCommand;
use Stolt\LeanPackage\GitattributesFileRepository;
use Stolt\LeanPackage\Helpers\Str as OsHelper;
use Stolt\LeanPackage\Presets\Finder;
use Stolt\LeanPackage\Presets\PhpPreset;
use Stolt\LeanPackage\Tests\TestCase;
use Zenstruck\Console\Test\TestCommand;

final class CreateCommandTest extends TestCase
{
    protected function setUp(): void
    {
        $this->setUpTemporaryDirectory();
    }

    protected function tearDown(): void
    {
        $this->removeDirectory($this->temporaryDirectory);
    }

    #[Test]
    public function createsNewGitattributesFileWithHeaderAndExpectedContent(): void
    {
        if ((new OsHelper())->isWindows()) {
            $this->markTestSkipped('Skipping test on Windows systems');
        }

        $analyser = (new Analyser(new Finder(new PhpPreset())))->setDirectory($this->temporaryDirectory);
        $repository = new GitattributesFileRepository($analyser);
        $command = new CreateCommand($analyser, $repository);

        $artifactFilenames = ['README.md', '.gitignore'];

        $this->createTemporaryFiles(
            $artifactFilenames,
            ['tests']
        );

        TestCommand::for($command)
            ->addArgument($this->temporaryDirectory)
            ->execute()
            ->assertSuccessful()
            ->assertOutputContains("A .gitattributes file has been created at {$this->temporaryDirectory}.");

        $gitattributesPath = $this->temporaryDirectory . DIRECTORY_SEPARATOR . '.gitattributes';
        $this->assertFileExists($gitattributesPath);

        $content = (string) \file_get_contents($gitattributesPath);

        // Header should be present (created files use "generated" header)
        $this->assertStringContainsString(
            '# This file was generated by the lean package validator (http://git.io/lean-package-validator).',
            $content
        );

        // Sanity check: expected export-ignores likely include .gitattributes itself and tests/
        $this->assertStringContainsString('.gitattributes', $content);
        $this->assertStringContainsString('tests/', $content);
        $this->assertStringContainsString('export-ignore', $content);
    }

    #[Test]
    public function printsExpectedContentWithoutWritingAFile(): void
    {
        $analyser = (new Analyser(new Finder(new PhpPreset())))->setDirectory($this->temporaryDirectory);
        $repository = new GitattributesFileRepository($analyser);
        $command = new CreateCommand($analyser, $repository);

        $artifactFilenames = ['README.md', '.gitignore'];

        $this->createTemporaryFiles(
            $artifactFilenames,
            ['tests']
        );

        $result = TestCommand::for($command)
            ->addArgument($this->temporaryDirectory)
            ->addOption('dry-run')
            ->execute()
            ->assertSuccessful();

        $output = $result->output();

        $this->assertStringContainsString('export-ignore', $output);
        $this->assertStringNotContainsString('has been created', $output);

        $this->assertFileDoesNotExist($this->temporaryDirectory . DIRECTORY_SEPARATOR . '.gitattributes');
    }

    #[Test]
    public function failsIfGitattributesAlreadyExists(): void
    {
        if ((new OsHelper())->isWindows()) {
            $this->markTestSkipped('Skipping test on Windows systems');
        }

        $gitattributesContent = <<<CONTENT
* text=auto eol=lf

phpspec.yml.dist export-ignore
specs/ export-ignore
CONTENT;

        $this->createTemporaryGitattributesFile($gitattributesContent);

        $analyser = (new Analyser(new Finder(new PhpPreset())))->setDirectory($this->temporaryDirectory);
        $repository = new GitattributesFileRepository($analyser);
        $command = new CreateCommand($analyser, $repository);

        TestCommand::for($command)
            ->addArgument($this->temporaryDirectory)
            ->execute()
            ->assertFaulty()
            ->assertOutputContains('A .gitattributes file already exists. Use the update command to modify it.');
    }
}
