<?php

declare(strict_types=1);

namespace Stolt\LeanPackage\Tests\Commands;

use PHPUnit\Framework\Attributes\Test;
use Stolt\LeanPackage\Analyser;
use Stolt\LeanPackage\Analysers\ClassicExportIgnoreAnalyser;
use Stolt\LeanPackage\Analysers\NegatedExportIgnoreAnalyser;
use Stolt\LeanPackage\Commands\CreateCommand;
use Stolt\LeanPackage\Gitattributes\FileRepository as GitattributesFileRepository;
use Stolt\LeanPackage\Helpers\Str as OsHelper;
use Stolt\LeanPackage\Presets\Finder;
use Stolt\LeanPackage\Presets\PhpPreset;
use Stolt\LeanPackage\Tests\TestCase;
use Zenstruck\Console\Test\TestCommand;

final class CreateCommandTest extends TestCase
{
    protected Analyser $analyser;

    protected function setUp(): void
    {
        $this->setUpTemporaryDirectory();

        $this->analyser = new Analyser(new ClassicExportIgnoreAnalyser(
            new Finder(new PhpPreset()),
            new GitattributesFileRepository($this->temporaryDirectory),
            $this->temporaryDirectory
        ));
        $this->analyser->getActualExportIgnoreAnalyser()->setDirectory($this->temporaryDirectory);
    }

    /**
     * @return CreateCommand
     */
    private function getCommandInstance(): CreateCommand
    {
        return new CreateCommand($this->analyser, new GitattributesFileRepository($this->temporaryDirectory));
    }

    protected function tearDown(): void
    {
        $this->removeDirectory($this->temporaryDirectory);
    }

    #[Test]
    public function failsForUnknownFlavour(): void
    {
        TestCommand::for($this->getCommandInstance())
            ->addArgument($this->temporaryDirectory)
            ->addOption('flavour', 'unknown')
            ->execute()
            ->assertFaulty()
            ->assertOutputContains('Invalid flavour specified. Use classic or negated');
    }

    #[Test]
    public function createsAGitattributesFileWithNegatedExportIgnoreDirectives(): void
    {
        $artifactFilenames = ['LICENSE.md', '.gitignore', 'composer.json'];

        $this->createTemporaryFiles(
            $artifactFilenames,
            ['tests', 'src', 'bin']
        );

        $this->createTemporaryFilesInDirectory($this->temporaryDirectory . DIRECTORY_SEPARATOR  . 'bin', ['lpv']);
        $this->createTemporaryFilesInDirectory($this->temporaryDirectory . DIRECTORY_SEPARATOR  . 'src', ['Fake.php', 'AnotherFake.php']);

        TestCommand::for($this->getCommandInstance())
            ->addArgument($this->temporaryDirectory)
            ->addOption('flavour', NegatedExportIgnoreAnalyser::EXPORT_IGNORE_NEGATED)
            ->addOption('keep-license')
            ->execute()
            ->assertSuccessful();

        $expectedGitattributesContent = <<<CONTENT
# This file was generated by the lean package validator (http://git.io/lean-package-validator).

* text=auto eol=lf

* export-ignore

bin/ -export-ignore
bin/lpv -export-ignore
composer.json -export-ignore
LICENSE.md -export-ignore
src/ -export-ignore
src/** -export-ignore
CONTENT;

        $this->assertFileExists($this->temporaryDirectory . DIRECTORY_SEPARATOR . '.gitattributes');
        $this->assertStringContainsStringIgnoringLineEndings(
            $expectedGitattributesContent,
            \file_get_contents($this->temporaryDirectory . DIRECTORY_SEPARATOR . '.gitattributes')
        );
    }

    #[Test]
    public function createsNewGitattributesFileWithHeaderAndExpectedContent(): void
    {
        if ((new OsHelper())->isWindows()) {
            $this->markTestSkipped('Skipping test on Windows systems');
        }

        $artifactFilenames = ['README.md', '.gitignore'];

        $this->createTemporaryFiles(
            $artifactFilenames,
            ['tests']
        );

        TestCommand::for($this->getCommandInstance())
            ->addArgument($this->temporaryDirectory)
            ->execute()
            ->assertSuccessful()
            ->assertOutputContains('A .gitattributes file has been created in ' . (\realpath($this->temporaryDirectory) ?: $this->temporaryDirectory) . '.');

        $gitattributesPath = $this->temporaryDirectory . DIRECTORY_SEPARATOR . '.gitattributes';
        $this->assertFileExists($gitattributesPath);

        $content = (string) \file_get_contents($gitattributesPath);

        // Header should be present (created files use "generated" header)
        $this->assertStringContainsString(
            '# This file was generated by the lean package validator (http://git.io/lean-package-validator).',
            $content
        );

        // Sanity check: expected export-ignores likely include .gitattributes itself and tests/
        $this->assertStringContainsString('.gitattributes', $content);
        $this->assertStringContainsString('tests/', $content);
        $this->assertStringContainsString('export-ignore', $content);
    }

    #[Test]
    public function printsExpectedContentWithoutWritingAFile(): void
    {
        $artifactFilenames = ['README.md', '.gitignore'];

        $this->createTemporaryFiles(
            $artifactFilenames,
            ['tests']
        );

        $result = TestCommand::for($this->getCommandInstance())
            ->addArgument($this->temporaryDirectory)
            ->addOption('dry-run')
            ->execute()
            ->assertSuccessful();

        $output = $result->output();

        $this->assertStringContainsString('export-ignore', $output);
        $this->assertStringNotContainsString('has been created', $output);

        $this->assertFileDoesNotExist($this->temporaryDirectory . DIRECTORY_SEPARATOR . '.gitattributes');
    }

    #[Test]
    public function failsIfGitattributesAlreadyExists(): void
    {
        if ((new OsHelper())->isWindows()) {
            $this->markTestSkipped('Skipping test on Windows systems');
        }

        $gitattributesContent = <<<CONTENT

phpspec.yml.dist export-ignore
specs/ export-ignore
CONTENT;

        $this->createTemporaryGitattributesFile($gitattributesContent);

        TestCommand::for($this->getCommandInstance())
            ->addArgument($this->temporaryDirectory)
            ->execute()
            ->assertFaulty()
            ->assertOutputContains('A .gitattributes file already exists. Use the update command to modify it.');
    }

    #[Test]
    public function outputsJsonOnSuccessWhenAgenticRunOptionIsSet(): void
    {
        if ((new OsHelper())->isWindows()) {
            $this->markTestSkipped('Skipping test on Windows systems');
        }

        $this->createTemporaryFiles(['README.md', '.gitignore'], ['tests']);

        $result = TestCommand::for($this->getCommandInstance())
            ->addArgument($this->temporaryDirectory)
            ->addOption('agentic-run')
            ->execute()
            ->assertSuccessful();

        $json = \json_decode(\trim($result->output()), true);

        $this->assertIsArray($json);
        $this->assertSame('create', $json['command']);
        $this->assertSame('success', $json['status']);
        $this->assertStringContainsString($this->temporaryDirectory, $json['message']);
        $this->assertArrayHasKey('gitattributes_file_path', $json);
    }

    #[Test]
    public function outputsJsonOnFailureWhenAgenticRunOptionIsSet(): void
    {
        $gitattributesContent = <<<CONTENT

phpspec.yml.dist export-ignore
specs/ export-ignore
CONTENT;
        $this->createTemporaryGitattributesFile($gitattributesContent);

        $result = TestCommand::for($this->getCommandInstance())
            ->addArgument($this->temporaryDirectory)
            ->addOption('agentic-run')
            ->execute()
            ->assertFaulty();

        $json = \json_decode(\trim($result->output()), true);

        $this->assertIsArray($json);
        $this->assertSame('create', $json['command']);
        $this->assertSame('failure', $json['status']);
        $this->assertStringContainsString('already exists', $json['message']);
    }
}
