<?php

declare(strict_types=1);

namespace Stolt\LeanPackage\Tests\Commands;

use PHPUnit\Framework\Attributes\Test;
use Stolt\LeanPackage\Analyser;

use Stolt\LeanPackage\Analysers\ClassicExportIgnoreAnalyser;
use Stolt\LeanPackage\Commands\UpdateCommand;
use Stolt\LeanPackage\Gitattributes\FileRepository as GitattributesFileRepository;
use Stolt\LeanPackage\Helpers\Str as OsHelper;
use Stolt\LeanPackage\Presets\Finder;
use Stolt\LeanPackage\Presets\PhpPreset;
use Stolt\LeanPackage\Tests\TestCase;
use Zenstruck\Console\Test\TestCommand;

final class UpdateCommandTest extends TestCase
{
    protected Analyser $analyser;

    /**
     * @return UpdateCommand
     */
    private function getCommandInstance(): UpdateCommand
    {
        $repository = new GitattributesFileRepository($this->temporaryDirectory);
        return new UpdateCommand($this->analyser, $repository);
    }

    protected function setUp(): void
    {
        $this->setUpTemporaryDirectory();

        $this->analyser = new Analyser(
            new ClassicExportIgnoreAnalyser(new Finder(new PhpPreset()), new GitattributesFileRepository($this->temporaryDirectory))
        );
        $this->analyser->getActualExportIgnoreAnalyser()->setDirectory($this->temporaryDirectory);
    }

    protected function tearDown(): void
    {
        $this->removeDirectory($this->temporaryDirectory);
        $this->clearAgenticEnvironment();
    }

    #[Test]
    public function updatesExistingGitattributesAndReplacesHeader(): void
    {
        if ((new OsHelper())->isWindows()) {
            $this->markTestSkipped('Skipping test on Windows systems');
        }

        $artifactFilenames = ['.gitignore'];

        $this->createTemporaryFiles(
            $artifactFilenames,
            ['tests', '.github']
        );

        $gitattributesContent = <<<CONTENT
# This file was generated by the lean package validator (http://git.io/lean-package-validator).

.gitattributes export-ignore
.github/ export-ignore
tests/ export-ignore
CONTENT;

        $this->createTemporaryGitattributesFile($gitattributesContent);

        TestCommand::for($this->getCommandInstance())
            ->addArgument($this->temporaryDirectory)
            ->execute()
            ->assertSuccessful()
            ->assertOutputContains('The .gitattributes file in ' . (\realpath($this->temporaryDirectory) ?: $this->temporaryDirectory) . ' has been updated.');

        $gitattributesPath = $this->temporaryDirectory . DIRECTORY_SEPARATOR . '.gitattributes';
        $this->assertFileExists($gitattributesPath);

        $content = (string) \file_get_contents($gitattributesPath);

        // Header should be the "modified" one after update
        $this->assertStringContainsString(
            '# This file was partly modified by the lean package validator (http://git.io/lean-package-validator).',
            $content
        );

        // Sanity: should still contain export-ignore entries and likely 'tests/' gets added
        $this->assertStringContainsString('.gitattributes', $content);
        $this->assertStringContainsString('.github/', $content);
        $this->assertStringContainsString('tests/', $content);
        $this->assertStringContainsString('export-ignore', $content);
    }
    #[Test]
    public function failsWhenNoGitattributesFileIsPresent(): void
    {
        if ((new OsHelper())->isWindows()) {
            $this->markTestSkipped('Skipping test on Windows systems');
        }

        // Remove the file
        $gitattributesFile = $this->temporaryDirectory . DIRECTORY_SEPARATOR . '.gitattributes';
        if (\file_exists($gitattributesFile)) {
            \unlink($gitattributesFile);
        }

        TestCommand::for($this->getCommandInstance())
            ->addArgument($this->temporaryDirectory)
            ->execute()
            ->assertFaulty()
            ->assertOutputContains('No .gitattributes file found. Use the create command to create one first.');
    }

    #[Test]
    public function printsExpectedContentWithoutWritingAFile(): void
    {
        $artifactFilenames = ['README.md', '.gitignore', 'phpunit.xml.dist'];

        $this->createTemporaryFiles(
            $artifactFilenames,
            ['tests']
        );

        $result = TestCommand::for($this->getCommandInstance())
            ->addArgument($this->temporaryDirectory)
            ->addOption('dry-run')
            ->addOption('align-export-ignores')
            ->execute()
            ->assertSuccessful();

        $output = $result->output();

        $this->assertStringContainsString('export-ignore', $output);
        $this->assertStringNotContainsString('has been updated', $output);

        $this->assertFileDoesNotExist($this->temporaryDirectory . DIRECTORY_SEPARATOR . '.gitattributes');
    }
    #[Test]
    public function outputsJsonOnSuccessInAnAgenticRun(): void
    {
        if ((new OsHelper())->isWindows()) {
            $this->markTestSkipped('Skipping test on Windows systems');
        }

        $this->createTemporaryFiles(['.gitignore'], ['tests', '.github']);

        $gitattributesContent = <<<CONTENT
.gitattributes export-ignore
.github/ export-ignore
tests/ export-ignore
CONTENT;
        $this->createTemporaryGitattributesFile($gitattributesContent);

        \putenv('COPILOT_MODEL=1');

        $result = TestCommand::for($this->getCommandInstance())
            ->addArgument($this->temporaryDirectory)
            ->execute()
            ->assertSuccessful();

        $json = \json_decode(\trim($result->output()), true);

        $this->assertIsArray($json);
        $this->assertSame('update', $json['command']);
        $this->assertSame('success', $json['status']);
        $this->assertStringContainsString($this->temporaryDirectory, $json['message']);
        $this->assertArrayHasKey('gitattributes_file_path', $json);
    }

    #[Test]
    public function outputsJsonOnFailureInAnAgenticRun(): void
    {
        if ((new OsHelper())->isWindows()) {
            $this->markTestSkipped('Skipping test on Windows systems');
        }

        $gitattributesFile = $this->temporaryDirectory . DIRECTORY_SEPARATOR . '.gitattributes';
        if (\file_exists($gitattributesFile)) {
            \unlink($gitattributesFile);
        }

        \putenv('COPILOT_MODEL=1');

        $result = TestCommand::for($this->getCommandInstance())
            ->addArgument($this->temporaryDirectory)
            ->execute()
            ->assertFaulty();

        $json = \json_decode(\trim($result->output()), true);

        $this->assertIsArray($json);
        $this->assertSame('update', $json['command']);
        $this->assertSame('failure', $json['status']);
        $this->assertStringContainsString('No .gitattributes file found', $json['message']);
    }

    #[Test]
    public function groupsNonExportIgnoreDirectivesInSeparateSection(): void
    {
        $this->createTemporaryFiles([
            '.gitignore',
            '.editorconfig',
            '.gitattributes',
        ]);

        $gitattributesContent = <<<CONTENT
* text=auto eol=lf

.gitattributes export-ignore
composer.lock diff=json
.gitignore export-ignore
CHANGELOG.md merge=union
.editorconfig export-ignore
CONTENT;

        $this->createTemporaryGitattributesFile($gitattributesContent);

        $result = TestCommand::for($this->getCommandInstance())
            ->addArgument($this->temporaryDirectory)
            ->addOption('group')
            ->addOption('align-export-ignores')
            ->addOption('dry-run')
            ->execute()
            ->assertSuccessful();

        $output = $result->output();

        $this->assertStringContainsString('* text=auto eol=lf', $output);
        $this->assertStringContainsString('composer.lock diff=json', $output);
        $this->assertStringContainsString('CHANGELOG.md merge=union', $output);
        $this->assertStringContainsString('export-ignore', $output);

        $nonExportIgnoresPosition = \strpos($output, 'composer.lock diff=json');
        $exportIgnorePosition = \strpos($output, 'export-ignore');

        $this->assertNotFalse($nonExportIgnoresPosition);
        $this->assertNotFalse($exportIgnorePosition);
        $this->assertLessThan($exportIgnorePosition, $nonExportIgnoresPosition);
    }

    #[Test]
    public function groupsNonExportIgnoreDirectivesAndWritesFile(): void
    {
        if ((new OsHelper())->isWindows()) {
            $this->markTestSkipped('Skipping test on Windows systems');
        }

        $this->createTemporaryFiles([
            '.gitignore',
            '.editorconfig',
            '.gitattributes',
        ]);

        $gitattributesContent = <<<CONTENT
* text=auto eol=lf

.gitattributes export-ignore
composer.lock diff=json
.gitignore export-ignore
CHANGELOG.md merge=union
.editorconfig export-ignore
CONTENT;

        $this->createTemporaryGitattributesFile($gitattributesContent);

        TestCommand::for($this->getCommandInstance())
            ->addArgument($this->temporaryDirectory)
            ->addOption('group')
            ->addOption('align-export-ignores')
            ->execute()
            ->assertSuccessful()
            ->assertOutputContains('The .gitattributes file in ' . (\realpath($this->temporaryDirectory) ?: $this->temporaryDirectory) . ' has been updated.');

        $written = (string) \file_get_contents($this->temporaryDirectory . '/.gitattributes');

        $this->assertStringContainsString('* text=auto eol=lf', $written);
        $this->assertStringContainsString('composer.lock diff=json', $written);
        $this->assertStringContainsString('CHANGELOG.md merge=union', $written);
        $this->assertStringContainsString('export-ignore', $written);

        $nonExportIgnoresPosition = \strpos($written, 'composer.lock diff=json');
        $exportIgnorePosition = \strpos($written, 'export-ignore');

        $this->assertNotFalse($nonExportIgnoresPosition);
        $this->assertNotFalse($exportIgnorePosition);
        $this->assertLessThan($exportIgnorePosition, $nonExportIgnoresPosition);
    }

    #[Test]
    public function itKeepsNonExportIgnoreContentAndRemovesAllStaleEntries(): void
    {
        $this->createTemporaryFiles([
            '.gitignore',
            '.editorconfig',
            '.gitattributes',
            '.gitignore',
            'phpunit.xml.dist',
            'pint.json',
            'README.md',
            'License.txt'
        ], ['tests', '.github']);

        $gitattributesContent = <<<CONTENT
* text=auto

/tests export-ignore
.editorconfig export-ignore
.gitattributes export-ignore
.gitignore export-ignore
.styleci.yml export-ignore
.travis.yml export-ignore
phpunit.xml export-ignore
README.md export-ignore
CONTENT;

        $this->createTemporaryGitattributesFile($gitattributesContent);

        $expectedUpdatedGitattributesContent = <<<CONTENT
# This file was partly modified by the lean package validator (http://git.io/lean-package-validator).

* text=auto

.editorconfig    export-ignore
.gitattributes   export-ignore
.github/         export-ignore
.gitignore       export-ignore
phpunit.xml.dist export-ignore
pint.json        export-ignore
README.md        export-ignore
tests/           export-ignore
CONTENT;

        TestCommand::for($this->getCommandInstance())
            ->addArgument($this->temporaryDirectory)
            ->addOption('keep-license')
            ->addOption('align-export-ignores')
            ->execute()
            ->assertSuccessful();

        $this->assertStringEqualsFile(
            $this->temporaryDirectory . '/.gitattributes',
            $expectedUpdatedGitattributesContent
        );
    }
}
