<?php

declare(strict_types=1);

namespace Stolt\LeanPackage;

use Stolt\LeanPackage\Exceptions\GitattributesCreationFailed;

final class GitattributesFileRepository
{
    public const GENERATED_HEADER = '# This file was generated by the lean package validator (http://git.io/lean-package-validator).';
    public const MODIFIED_HEADER  = '# This file was partly modified by the lean package validator (http://git.io/lean-package-validator).';

    protected Analyser $analyser;

    public function __construct(Analyser $analyser)
    {
        $this->analyser = $analyser;
    }

    /**
     * Create the gitattributes file.
     *
     * @param  string  $content The content of the gitattributes file
     * @param  bool    $withHeader Whether to prepend the generated header
     * @throws GitattributesCreationFailed
     * @return string
     *
     */
    public function createGitattributesFile(string $content, bool $withHeader = true): string
    {
        // Ensure the generated or modified by header is present when requested
        if ($withHeader) {
            $content = $this->applyOverwriteHeaderPolicy($content);
        }

        $bytesWritten = file_put_contents(
            $this->analyser->getGitattributesFilePath(),
            $content
        );

        if ($bytesWritten) {
            $content = 'Created a .gitattributes file with the shown content:'
                . PHP_EOL . '<info>' . $content . '</info>';

            return PHP_EOL . PHP_EOL . $content;
        }

        $message = 'Creation of .gitattributes file failed.';
        throw new GitattributesCreationFailed($message);
    }

    /**
     * Overwrite an existing gitattributes file.
     *
     * @param  string  $content The content of the gitattributes file
     * @throws GitattributesCreationFailed
     * @return string
     *
     */
    public function overwriteGitattributesFile(string $content): string
    {
        // Apply header policy before writing (generated → partly modified).
        $content = $this->applyOverwriteHeaderPolicy($content);

        $bytesWritten = file_put_contents(
            $this->analyser->getGitattributesFilePath(),
            $content
        );

        if ($bytesWritten) {
            $content = 'Overwrote it with the shown content:'
                . PHP_EOL . '<info>' . $content . '</info>';

            return PHP_EOL . PHP_EOL . $content;
        }

        $message = 'Overwrite of .gitattributes file failed.';
        throw new GitattributesCreationFailed($message);
    }

    /**
     * Prepare .gitattributes content for overwriting by adjusting the header.
     * If the present file contains the "generated by" header, replace it with
     * the "partly modified by" header in the given content-to-write.
     */
    public function applyOverwriteHeaderPolicy(string $contentToWrite): string
    {
        $gitattributesPath = $this->analyser->getGitattributesFilePath();

        if (!\is_file($gitattributesPath)) {
            return self::GENERATED_HEADER . PHP_EOL . PHP_EOL . $contentToWrite;
        }

        if (\str_contains($contentToWrite, self::GENERATED_HEADER)) {
            return \str_replace(self::GENERATED_HEADER, self::MODIFIED_HEADER, $contentToWrite);
        }

        if ((\str_contains($contentToWrite, self::MODIFIED_HEADER) === false) && (\str_contains($contentToWrite, self::GENERATED_HEADER) === false)) {
            return self::MODIFIED_HEADER . PHP_EOL . PHP_EOL . $contentToWrite;
        }

        return $contentToWrite;
    }
}
