name: distribute-cli

on:
  push:
    tags:
      - 'v*'

jobs:
    tests:
        name: distribute-cli
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php:
                    - "8.1"

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"

            -   name: Install Composer dependencies
                run: composer install --no-progress --prefer-dist --optimize-autoloader && composer require --dev --with-all-dependencies humbug/box

            -   name: Build PHAR
                run: vendor/humbug/box/bin/box compile

            -   name: Check generated PHAR
                run: bin/lean-package-validator.phar

            -   name: Create Release
                id: create_release
                uses: actions/create-release@v1
                env:
                   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  draft: false
                  prerelease: false

            -   name: Upload generated PHAR
                uses: actions/upload-release-asset@v1
                env:
                   GITHUB_TOKEN: ${{ github.token }}
                with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: bin/lean-package-validator.phar
                  asset_name: lean-package-validator.phar
                  asset_content_type: application/gzip
