name: distribute

on:
  push:
    tags:
      - 'v*'

jobs:
    tests:
        name: distribute
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php:
                    - "8.1"

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"

            -   name: Install Composer dependencies
                run: composer install --no-progress --prefer-dist --optimize-autoloader

            -   name: Install Box Phar bundler
                run: wget --quiet https://github.com/box-project/box/releases/download/4.3.8/box.phar && sudo mv box.phar /usr/bin/box && sudo chmod u+x /usr/bin/box
                shell: bash

            -   name: Build PHAR
                run: /usr/bin/box compile

            -   name: Check generated PHAR
                run: bin/lean-package-validator.phar --version

            -   name: Create Release
                uses: softprops/action-gh-release@v1
                if: startsWith(github.ref, 'refs/tags/')
                with:
                    files: bin/lean-package-validator.phar
