name: lint

on: push

jobs:
    tests:
        name: lint
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php:
                    - "8.1"

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"

            -   name: Install Composer dependencies
                run: composer install --no-progress --prefer-dist --optimize-autoloader

            -   name: Check coding styles
                run: composer run-script lpv:cs-lint

#            -   name: Check leanness of package
#                uses: raphaelstolt/lean-package-validator-action@v0.1.0
#                with:
#                    php-version: "${{ matrix.php }}"
#                    lpv-version: "3.0.0"
